# Generated by Django 6.0.5 on 2026-05-07 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=20)),
                ('difficulty', models.CharField(max_length=10)),
                ('score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-percentage', '-score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('basics', 'Python 기초'), ('oop', '객체지향 프로그래밍'), ('algorithms', '자료구조/알고리즘'), ('advanced', '고급 Python'), ('practical', '실무/면접')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', '입문'), ('medium', '중급'), ('hard', '고급')], max_length=10)),
                ('question_text', models.TextField()),
                ('hint', models.TextField()),
                ('answer_key', models.TextField(help_text='Comma-separated key points for evaluation')),
                ('code_snippet', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64, unique=True)),
                ('category', models.CharField(max_length=20)),
                ('difficulty', models.CharField(max_length=10)),
                ('total_questions', models.IntegerField(default=5)),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField()),
                ('result', models.CharField(choices=[('correct', '정답'), ('partial', '부분 정답'), ('incorrect', '오답')], max_length=10)),
                ('score_earned', models.IntegerField(default=0)),
                ('ai_feedback', models.TextField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.quizsession')),
            ],
        ),
    ]
