# Generated by Django 6.0.5 on 2026-05-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.CharField(choices=[('ai', 'AI 생성'), ('preset', '사전 등록')], default='ai', max_length=10),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='mode',
            field=models.CharField(choices=[('ai', 'AI 생성'), ('db', 'DB 문제')], default='ai', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('basics', 'Python 기초'), ('oop', '객체지향 프로그래밍'), ('algorithms', '자료구조/알고리즘'), ('advanced', '고급 Python'), ('practical', '실무/면접'), ('docker', 'Docker'), ('git', 'Git'), ('mixed', 'Python 전반')], max_length=20),
        ),
    ]
